### ISSUE TITLE
SpamExperts extension not working with Plesk 17 (Onyx)

### ISSUE THREAD

**Issue by mrdemc** [SpamExperts/plesk-extension#2]
When domain list is viewed, the list remains empty. "There are no domains on this server."

> PHP version:	
OK!
PHP extensions:	
OK!
Configuration permissions:	
OK!
Panel version:	
OK!
Addon version:	
OK!
Hashes:	
OK!
Hooks:	
OK!
Symlinks:	
OK!
Controlpanel API:
Unable to communicate with the controlpanel API	
CRITICAL
Spamfilter API:	
OK!
Symlink to PHP5 binary:	
OK!

**Comment by dbistriceanu** [comment]
The additional information you've added seems to be the "Run diagnostics" output of our Plesk addon which does not support Plesk 17, not from the Plesk extension. And the same applies for the text you see when the domains list is empty. Can you please clarify this?

**Comment by mrdemc** [comment]
That is correct @dbistriceanu I notice the difference now 😉
