### ISSUE TITLE
Upgrade fails from APS 2.0-10 to version 2.0-15

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/plesk-extension#22]
When trying to upgrade from APS 2.0-10 to version 2.0-15 this error occurs:

```
Task ID
13893964
Task name
Upgrading resources of application 'SpamExperts'
Task description
Upgrading resources of application SpamExperts 2.0-10 to version 2.0-15
Belongs to groups
2699:154194302
Parent task ID
13893963
Queue status
Failed
Start not earlier than
Jan-25-2017 20:03
Method name
taskUpgradeApp2x on SCREF:SaaSManagerTasks:0
Last execution output
Internal error: APSC: Upgrade to ver. 2.0-15 : resource 399ad95e-0941-4e38-9d38-9bd9e02beea7 of type 'service' (http://aps.spamexperts.com/app/service/1.3) for APS application 'SpamExperts-2.0-15' : The operation with name 'onContextAvailable' is not found..
```
Aps support suggested the isue was due to the domain aciel-geomatics.com. The domain exists in SE, it shows in Odin as not protected. When trying to unprotect the domain and update the following error is seen:

`Internal error: APSC: Upgrade to ver. 2.0-15 : resource 399ad95e-0941-4e38-9d38-9bd9e02beea7 of type 'service' (http://aps.spamexperts.com/app/service/1.3) for APS application 'SpamExperts-2.0-15' : Internal Server Error: Unknown method "onContextAvailabeSubscribe"..`

More logs attached.

[logs.zip](https://github.com/SpamExperts/plesk-extension/files/734700/logs.zip)

**Comment by for93t** [comment]
This should have been reported for https://github.com/SpamExperts/aps2-addon
