### ISSUE TITLE
Add formatted description to the extension

### ISSUE THREAD

**Issue by for93t** [SpamExperts/plesk-extension#23]
Plesk Extensions SDK developers have recently added possibility to have formatted descriptions (in Markdown format): 

https://docs.plesk.com/en-US/onyx/extensions-guide/plesk-extensions-basics/extension-structure.71076/#o77961

We would want to improve the existing description to add more info about our extension.

**Comment by tonyandrewmeyer** [comment]
No UX and no QA?

**Comment by for93t** [comment]
Yes, no UX and no QA at this point due to the following reasons:

- The only UX part that could be done here is providing texts and formatting. They already provided the text (the one from the [existing description](https://github.com/SpamExperts/plesk-extension/blob/master/meta.xml#L5) was used). No new text was added, except system requirements which are just a list. No special formatting was introduced. Nothing new in terms of UX that's why they were not involved.
- This description is used in the [Plesk extensions catalog](https://ext.plesk.com) only so there is no any way for the QA to test the changes.
- The package reviewer from Plesk insisted on adding that DESCRIPTION.md file into the package as it's important for them to have the description provided in that way  as they are about to roll out some changes in their platform.
- Plesk extensions review team does extensive testing of packages before publication and they are pretty reliable on that so why do a double work?

We definitely can have an extensive description with rich formatting, screenshots and so on but it's not a priority at the moment. I'm going to ask the Marketing team to assist with this for one of the next releases of the extension.

**Comment by tonyandrewmeyer** [comment]
This feature was also done outside of the milestone. If a feature needs to be pushed, we have procedures for that. @alexkiro can you please review what needs to be done here?
