### ISSUE TITLE
SpamFilter API revision is rev.UNKNOWN

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/plesk-extension#30]
### Version information

N/A

### Steps to replicate

1. Install and configure extension
2. Go to 'Support' tab of extension

### Actual result

In 'Diagnostics' section SpamFilter API: rev.UNKNOWN

### Expected result

API version is shown.

**Comment by for93t** [comment]
Sorry, I cannot reproduce this on latest extension version.
