### ISSUE TITLE
Credentials are overwritten when a domain is migrated

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/plesk-extension#31]
### Version information
Plesk Onyx
Plesk: v17.0.17 (Unix)
PHP version: 5.6.27
Extension version: v1.1-0

### Steps to replicate

Did not check if this replicates

 1. Install extension on one Plesk server (server1)
 1. Install extension on one Plesk server (server2)
 1. Configure server1 extension with a user (user1)
 1. Configure server2 extension with a user (user2)
 1. Add domain on server1
 1. Use Plesk migrator to migrate domain from server1 to server2 
 1. Check extension settings on server2.

### Actual result

Using the Plesk migrator to move one domain between servers, the general SpamExperts module configuration is also migrated, so the main user and password configured in the module to access to their spamexperts local cloud is overwritten on the destination node.

### Expected result
This should not be happening, from the client's perspective.

### Other notes
Whmcs #156235

**Comment by for93t** [comment]
I've sent an email to Plesk support asking for an explanation of such behavior of the panel. Waiting for a reply from them.

**Comment by for93t** [comment]
Described issue is a known issue on Plesk Migrator side (ID PMT-3586) it will be fixed in upcoming release of Plesk Migrator in about 2 weeks.
