### ISSUE TITLE
Plesk extension not removing old MX record

### ISSUE THREAD

**Issue by AlexandraSE** [SpamExperts/plesk-extension#32]
### Version information

Plesk: v17.0.17 (Unix)
Extension version: v1.1-0

### Steps to replicate

 1. Add new domain to the latest Plesk Extension
 2. Once you did so, the domain will be uploaded to the SpamExperts interface and the new MX records will be added
 3. However, the old MX records will still be there

### Actual result

The old MX records are not removed

### Expected result
The domains should only have the new MX records added

**Comment by alexkiro** [comment]
Cannot be replicated.
