### ISSUE TITLE
Add a status column to the domain list 

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/plesk-extension#37]
We should add a status column to the domain list in the "Domains" tab instead of having alerts for each domain, as those can stack up a lot for large number of domains. _(This should likely work the same as we have in the cPanel addon)_
![screenshot from 2017-05-05 11-09-23](https://cloud.githubusercontent.com/assets/1538458/25738018/8038de0c-3183-11e7-8de0-b4a3faf31848.png)

**Comment by mihaipetrea** [comment]
Hi, please find the mockup for this task below. We added the new column for the status and we're using the icons that we had on the error message because some users are familiar with them and its no point in changing any of them.

![37---add-a-status-column-to-the-domain-list](https://user-images.githubusercontent.com/25821365/27676246-dfc60ce8-5cb5-11e7-85fb-11529f48db96.png)

**Comment by for93t** [comment]
In order to implement this properly so there are no performance issues with the extension (no API throttling with multiple parallel requests) the API needs a new feature implemented first. The internal ticket ID is `21382`.

**Comment by mihaipetrea** [comment]
Please see the entire flow below. The column will have a link named "Check status". When the user clicks on it, they will see the status for that domain. Hope everything is ok now :) 

![37---add-a-status-column-to-the-domain-list---1](https://user-images.githubusercontent.com/25821365/27729309-0e875b26-5d8e-11e7-8448-812bb5d0e533.png)
![37---add-a-status-column-to-the-domain-list---2](https://user-images.githubusercontent.com/25821365/27729311-109ac740-5d8e-11e7-9392-af45be00d20d.png)
![37---add-a-status-column-to-the-domain-list---3](https://user-images.githubusercontent.com/25821365/27729312-12c4d574-5d8e-11e7-9bb1-583d6cf65964.png)

**Comment by catalinDonici** [comment]
Verified.

**Comment by alexkiro** [comment]
This needs to stay open until it's:

 1. Re-verified
 2. Published in Plesk store.

**Comment by lorentina** [comment]
Re-verified. The new column works as expected.

**Comment by alexkiro** [comment]
New version published.
