### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by solucionesuno** [SpamExperts/plesk-extension#47]
### Version information
Versión: 1.2-0

### Steps to replicate

try to check status or open the panel. without succesfull

### Actual result

seems like the domain is not protected when it is.

### Expected result

Open control panel correctly.

**Comment by for93t** [comment]
@solucionesuno can you please add the following info so we could investigate the issue?

- Plesk panel version;
- The reported error, if any? A screenshot would help;
- Debug logs ([how to enable debug logging](https://docs.plesk.com/en-US/12.5/extensions-guide/testing-extensions.71114/), [where to obtain logs](https://support.plesk.com/hc/en-us/articles/213403509-Plesk-for-Linux-services-logs-and-configuration-files-#plesk)).

Thanks a lot for your cooperation!

**Comment by solucionesuno** [comment]
problem with api plesk. it was solved updating plesk. Versión 17.5.3 Actualización #47,
 
regards
