### ISSUE TITLE
Original MX record not removed after the domain is added

### ISSUE THREAD

**Issue by VicSpam01** [SpamExperts/plesk-extension#48]
### Version information

Plesk Version: Version 17.8.11
Extension Version: Version: 1.2-0
OS Version: CloudLinux 7.5
Kernel Version: 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64

### Steps to replicate

 1. Add a domain
 2. The domain is added correctly, the MX records are added but the original MX record is not removed

### Actual result

the original MX record is not removed

### Expected result

For the original MX record to be removed and only the filtering server's MX records to be kept

**Comment by for93t** [comment]
@VicSpam01 can we [obtain](https://github.com/SpamExperts/plesk-extension#troubleshooting) some logs related to the issue?

**Comment by for93t** [comment]
This looks to be a Pleask issue, not related to the way the extension works. Please reopen if there are more details about the case indicating that the current extension's behavior is wrong.
